"""identity provisional key retained

Revision ID: 267d4f9afedb
Revises: 950a49f718af
Create Date: 2026-08-18 16:43:58.034128
"""

from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401  (autogenerate uses it; empty revisions do not)
from alembic import op  # noqa: F401

revision: str = '267d4f9afedb'
down_revision: str | Sequence[str] | None = '950a49f718af'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identities', sa.Column('provisional_key', sa.String(length=128), nullable=True))
    op.create_index(
        op.f('ix_identities_provisional_key'),
        'identities',
        ['provisional_key'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identities_provisional_key'), table_name='identities')
    op.drop_column('identities', 'provisional_key')
    # ### end Alembic commands ###
