"""groups, group observations, policy documents, authz fields

Revision ID: 950a49f718af
Revises: c88e501e10b6
Create Date: 2026-08-18 13:06:33.830377
"""

from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401  (autogenerate uses it; empty revisions do not)
from alembic import op  # noqa: F401

revision: str = '950a49f718af'
down_revision: str | Sequence[str] | None = 'c88e501e10b6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('provider_identifier', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'provider_identifier')
    )
    op.create_index(
        op.f('ix_groups_provider_identifier'),
        'groups',
        ['provider_identifier'],
        unique=False,
    )
    op.create_table('group_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('arn', sa.String(length=2048), nullable=True),
    sa.Column('attached_policies', sa.JSON(), nullable=True),
    sa.Column('inline_policy_names', sa.JSON(), nullable=True),
    sa.Column('member_identifiers', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'group_id')
    )
    op.create_table('policy_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('policy_arn', sa.String(length=2048), nullable=False),
    sa.Column('policy_name', sa.String(length=255), nullable=False),
    sa.Column('aws_managed', sa.Boolean(), nullable=False),
    sa.Column('document', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'policy_arn')
    )
    op.add_column(
        'observations',
        sa.Column('role_last_used', sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        'observations',
        sa.Column('role_last_used_region', sa.String(length=64), nullable=True),
    )
    op.add_column('observations', sa.Column('trust_policy', sa.JSON(), nullable=True))
    op.add_column('observations', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('observations', sa.Column('attached_policies', sa.JSON(), nullable=True))
    op.add_column('observations', sa.Column('inline_policy_names', sa.JSON(), nullable=True))
    op.add_column('observations', sa.Column('group_names', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observations', 'group_names')
    op.drop_column('observations', 'inline_policy_names')
    op.drop_column('observations', 'attached_policies')
    op.drop_column('observations', 'tags')
    op.drop_column('observations', 'trust_policy')
    op.drop_column('observations', 'role_last_used_region')
    op.drop_column('observations', 'role_last_used')
    op.drop_table('policy_documents')
    op.drop_table('group_observations')
    op.drop_index(op.f('ix_groups_provider_identifier'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
