"""accounts, snapshots, identities, observations

Revision ID: c88e501e10b6
Revises: 917d2c873e27
Create Date: 2026-08-18 11:36:07.899637
"""

from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401  (autogenerate uses it; empty revisions do not)
from alembic import op  # noqa: F401

revision: str = 'c88e501e10b6'
down_revision: str | Sequence[str] | None = '917d2c873e27'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_account_id', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_accounts_provider_account_id'),
        'accounts',
        ['provider_account_id'],
        unique=True,
    )
    op.create_table('identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('provider_identifier', sa.String(length=128), nullable=False),
    sa.Column('provisional', sa.Boolean(), nullable=False),
    sa.Column('identity_type', sa.String(length=16), nullable=False),
    sa.Column('first_display_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'provider_identifier')
    )
    op.create_index(
        op.f('ix_identities_provider_identifier'),
        'identities',
        ['provider_identifier'],
        unique=False,
    )
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'source', 'captured_at')
    )
    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('arn', sa.String(length=2048), nullable=True),
    sa.Column('identity_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_enabled', sa.Boolean(), nullable=True),
    sa.Column('password_last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_last_changed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mfa_active', sa.Boolean(), nullable=True),
    sa.Column('key1_active', sa.Boolean(), nullable=True),
    sa.Column('key1_last_rotated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('key1_last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('key1_last_service', sa.String(length=64), nullable=True),
    sa.Column('key2_active', sa.Boolean(), nullable=True),
    sa.Column('key2_last_rotated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('key2_last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('key2_last_service', sa.String(length=64), nullable=True),
    sa.Column('cert1_active', sa.Boolean(), nullable=True),
    sa.Column('cert2_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'identity_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observations')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_identities_provider_identifier'), table_name='identities')
    op.drop_table('identities')
    op.drop_index(op.f('ix_accounts_provider_account_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
